# Generated by Django 2.2.3 on 2019-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='use_md',
            field=models.BooleanField(default=True, verbose_name='使用markdown语法'),
        ),
    ]
